### ISSUE TITLE
Generate text, background, and border classes from an arbitrary number of colours

### ISSUE THREAD

**Issue by AdamMurray** [AdamMurray/AUsefulSassLibrary#2]
Generate classes by iterating over a list of colours to output the required text, background, and border classes.

For example:
```scss

$colours-map: (
  brand: (
    colour: blue
  ),
  brand-two: (
    colour: red
  ),
  dark: (
    colour: black
  ),
  light: (
    colour: white
  )
);

@each $label, $map in $colours-map {
  .bg--#{$label} {
    background-color: map-get($map, colour);
  }
  
  .text--#{$label} {
    color: map-get($map, colour);
  }
  
  .border--#{$label} {
    border-color: map-get($map, colour);
  }
}
```

Reference:
* http://thesassway.com/intermediate/if-for-each-while
